import { stringify } from "yaml";
import type { SecurityPolicyIR } from "../types.js";
import { getScanner } from "../scanners/index.js";

export function compileCodeScanningWorkflowYAML(policy: SecurityPolicyIR): string {
  if (!policy.codeScanning.enabled || policy.codeScanning.scanners.length === 0) {
    return "";
  }

  const jobs: Record<string, unknown> = {};

  for (const scanner of policy.codeScanning.scanners) {
    const plugin = getScanner(scanner.tool);
    if (!plugin) continue;

    const steps: Array<Record<string, unknown>> = [
      {
        name: "Checkout repository",
        uses: "actions/checkout@v4"
      }
    ];

    if (policy.secretScanning.enabled) {
      steps.unshift({
        name: "Harden GitHub Actions Runner",
        uses: "step-security/harden-runner@v2",
        with: {
          "egress-policy": "audit"
        }
      });
    }

    const scannerSteps = plugin.buildSteps(scanner);
    steps.push(...scannerSteps);

    jobs[plugin.jobKey] = {
      name: plugin.jobName,
      "runs-on": "ubuntu-latest",
      "timeout-minutes": plugin.timeoutMinutes,
      steps
    };
  }


  if (Object.keys(jobs).length === 0) {
    return "";
  }

  const doc = {
    name: "Code Scanning & Security Analyzers",
    on: {
      push: { branches: ["main"] },
      pull_request: { branches: ["main"] }
    },
    permissions: {
      contents: "read",
      "security-events": "write",
      "pull-requests": "write"
    },
    concurrency: {
      group: "${{ github.workflow }}-${{ github.ref }}",
      "cancel-in-progress": true
    },
    jobs
  };

  const yamlBody = stringify(doc, {
    indent: 2,
    lineWidth: 0,
    simpleKeys: true,
    aliasDuplicateObjects: false
  });

  return `# ==============================================================================
# Generated by Auto GitHub Actions (auto-gha)
# Code Scanning & SAST Workflow (Level: ${policy.level})
# ==============================================================================

${yamlBody}`;
}
