import { stringify } from "yaml";
import type { SecurityPolicyIR } from "../types.js";

export function compileDependabotYAML(policy: SecurityPolicyIR): string {
  if (!policy.dependabot.enabled || policy.dependabot.ecosystems.length === 0) {
    return "";
  }

  const updates = policy.dependabot.ecosystems.map(target => ({
    "package-ecosystem": target.packageEcosystem,
    directory: target.directory,
    schedule: {
      interval: target.interval
    },
    "open-pull-requests-limit": 5,
    groups: {
      dependencies: {
        patterns: ["*"]
      }
    },
    ...(policy.level === "strict"
      ? {
          labels: ["dependencies", "security"],
          "versioning-strategy": "increase"
        }
      : {})
  }));

  const doc = {
    version: 2,
    updates
  };

  const yamlBody = stringify(doc, {
    indent: 2,
    lineWidth: 0,
    simpleKeys: true
  });

  return `# ==============================================================================
# Generated by Auto GitHub Actions (auto-gha)
# Dependabot Version & Security Update Configuration (Level: ${policy.level})
# ==============================================================================

${yamlBody}`;
}
